"""
lesion_postprocess.py
─────────────────────
Post-processes the lesion masks generated by lesion_segmentation.py.
It ensures the lesion is a single continuous white area, fills small black holes,
and removes isolated white regions outside the main lesion.

Input  : lesion_mask_*.png from data/abscess/raw/lesion_segmented/
Output : lesion_mask_*.png into data/abscess/raw/lesion_postprocessed/
"""

import os
import cv2
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
INPUT_DIR  = '../../../data/abscess/raw/lesion_segmented'
OUTPUT_DIR = '../../../data/abscess/raw/lesion_postprocessed'
CROUN_CROP_DIR = '../../../data/abscess/raw/croun_crops'

os.makedirs(OUTPUT_DIR, exist_ok=True)

def postprocess_mask(mask_path: str, filename: str) -> None:
    print(f"\nProcessing: {filename}")
    
    # Read the binary mask (grayscale)
    lesion_mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if lesion_mask is None:
        print(f"  [WARN] Could not read {mask_path} — skipping.")
        return

    # Ensure it's strictly binary
    _, lesion_mask = cv2.threshold(lesion_mask, 127, 255, cv2.THRESH_BINARY)

    # ── Post-processing to create a single continuous region ──────────────────
    # 1. Fill small black holes inside the lesion (Morphological Closing)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    lesion_mask = cv2.morphologyEx(lesion_mask, cv2.MORPH_CLOSE, kernel, iterations=3)

    # 2. Keep only the largest connected component to remove isolated white regions
    num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(lesion_mask, connectivity=8)
    if num_labels > 1:
        # Background is label 0. Find the largest component among labels 1 to num_labels-1.
        largest_label = 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA])
        lesion_mask = (labels == largest_label).astype(np.uint8) * 255
    else:
        lesion_mask = np.zeros_like(lesion_mask)

    # 3. Fill any remaining holes inside the largest connected component
    # cv2.RETR_EXTERNAL only retrieves the extreme outer contours.
    contours, _ = cv2.findContours(lesion_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    lesion_mask_filled = np.zeros_like(lesion_mask)
    if contours:
        cv2.drawContours(lesion_mask_filled, contours, -1, 255, thickness=cv2.FILLED)
    lesion_mask = lesion_mask_filled

    # ── Save output mask ──────────────────────────────────────────────────────
    mask_out_path = os.path.join(OUTPUT_DIR, filename)
    cv2.imwrite(mask_out_path, lesion_mask)
    print(f"  -> Post-processed mask saved: {mask_out_path}")

    # ── Generate overlay if possible ──────────────────────────────────────────
    # The original mask name is like "lesion_mask_texture_removed_1.png"
    # The original croun crop image might be just "texture_removed_1.png" or "1.png".
    # Let's assume we can derive the original filename by removing "lesion_mask_".
    orig_filename = filename.replace("lesion_mask_", "")
    orig_path = os.path.join(CROUN_CROP_DIR, orig_filename)
    
    if os.path.exists(orig_path):
        img_original = cv2.imread(orig_path, cv2.IMREAD_UNCHANGED)
        if img_original is not None:
            # Convert to grayscale to build BGR overlay
            if len(img_original.shape) == 2:
                gray_image = img_original
            elif img_original.shape[2] == 4:
                gray_image = cv2.cvtColor(img_original[:, :, :3], cv2.COLOR_BGR2GRAY)
            else:
                gray_image = cv2.cvtColor(img_original, cv2.COLOR_BGR2GRAY)
                
            overlay = cv2.cvtColor(gray_image, cv2.COLOR_GRAY2BGR)
            # Draw lesion region in bright yellow
            overlay[lesion_mask == 255] = [255, 255, 0] # BGR
            
            overlay_out_path = os.path.join(OUTPUT_DIR, f"overlay_{orig_filename}")
            cv2.imwrite(overlay_out_path, overlay)
            print(f"  -> Overlay saved: {overlay_out_path}")

if __name__ == '__main__':
    print("=" * 65)
    print("  Lesion Post-Processing (Hole Filling & Isolated Region Removal)")
    print("=" * 65)
    print(f"  Input  directory : {INPUT_DIR}")
    print(f"  Output directory : {OUTPUT_DIR}")
    print("=" * 65)

    supported_exts = ('.png', '.jpg', '.jpeg')
    
    # Process only the lesion masks
    files = [
        f for f in os.listdir(INPUT_DIR)
        if f.lower().startswith('lesion_mask_') and f.lower().endswith(supported_exts)
    ]

    if not files:
        print(f"\n[ERROR] No 'lesion_mask_*' images found in:\n  {INPUT_DIR}")
        print("        Run lesion_segmentation.py first.")
    else:
        print(f"\nFound {len(files)} mask(s) to process.\n")
        for filename in sorted(files):
            mask_path = os.path.join(INPUT_DIR, filename)
            postprocess_mask(mask_path, filename)

    print("\n" + "=" * 65)
    print("  Post-processing complete!")
    print("=" * 65)
